name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.12'

    - name: Build package
      run: python -m pip install setuptools wheel
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Upload Package
      uses: actions/upload-artifact@v4.3.6
      with:
        name: packages
        path: dist/
        if-no-files-found: error
        retention-days: 1


  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/awscli-local-win
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - name: Get packages
      uses: actions/download-artifact@v4.1.8
      with:
        name: packages
        path: dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1.9.0
    needs: build
